### ISSUE TITLE
Possible to remove stdout and only include stderr?

### ISSUE THREAD

**Issue by MichaelDacanay** [morlandi/django-ajax-datatable#103]
The ajax_datatable prints to stdout in the terminal when the AJAX queries for data. Is there a way to turn that off, and only show stderr?
<img width="717" alt="image" src="https://user-images.githubusercontent.com/18317412/222499688-3f842067-532d-437f-b727-48c6d92646f5.png">

**Comment by cnagytcorp** [comment]
maybe TRACE_QUERYSET, TRACE_QUERYDICT, TRACE_COLUMNDEFS in the [app settings](https://github.com/morlandi/django-ajax-datatable#id27) ?

**Comment by MichaelDacanay** [comment]
This is the correct answer. Thanks!
