### ISSUE TITLE
Changing Date formats

### ISSUE THREAD

**Issue by Palaniyappan12** [morlandi/django-ajax-datatable#107]
Hi, 
This might seem like a simple issue, but thanks in advance for clearing my doubt.
I'm currently working on a project, where I've have to include a Datefield in my datatable, but I can't change the default Date format in the Datatable, I found a way(attached below) to solve this, but it seems like a time consuming process. Is there any other way to solve this. 
 
![Screenshot 2023-03-11 at 11 22 07 AM](https://user-images.githubusercontent.com/127582153/224468083-e51ff80c-8095-413d-a59c-bb951f463236.png)

**Comment by morlandi** [comment]
Hello @Palaniyappan12 
since you've already overridden customize_row(), I would try going ahead as follows:

```
def customize_row(self, row, obj):
    ...
    row['date'] = obj.date.strftime('%Y-%m-%d')
```

Fully untested ;)

**Comment by MichaelDacanay** [comment]
This changes the date format from `2022-09-15 18:32:27+00:00` to `2022-09-15`.
