### ISSUE TITLE
set decimal separator as , and not .

### ISSUE THREAD

**Issue by faldonsergio** [morlandi/django-ajax-datatable#110]
How is possible to change default decimal separator and number of decimal? 
I've try to mass some parameter like:     language =  {
          "decimal": ",",
          "thousands": ".",
        },

but nothing.

**Comment by morlandi** [comment]
Hello @faldonsergio , did you check this:

https://github.com/morlandi/django-ajax-datatable#internationalization

If it works, please close the issue ;)

Good luck, Mario
