### ISSUE TITLE
Edit cell

### ISSUE THREAD

**Issue by mchessl** [morlandi/django-ajax-datatable#16]
Hi @morlandi !

I am trying to allow users to click on a cell, modify a cell and send back to django the new value.
I tried using [this tutorial](https://github.com/morlandi/django-ajax-datatable#adding-a-button-for-editing) but I haven't achieved my goal.

Do you know how I can could do such a thing ?

Thanks a lot :)

**Comment by morlandi** [comment]
Hello @mchessl 
I know datatables.net has an optional addon for editing in-place:

https://editor.datatables.net/

A Single developer licence costs $106.

In my example, I was just showing how to add a button to trigger an arbitrary action; then, I would rather open a modal form for editing the selected record.
For that, I normally use my own package:

https://github.com/morlandi/django-frontend-forms

you might want to take a look at.
Hope thie helps

**Comment by mchessl** [comment]
Many thanks @morlandi, I will go with your solution instead of editing in the cell !
Kind regards
