### ISSUE TITLE
Tried installing this library but it refused with the error AssertionError: No exception message supplied

### ISSUE THREAD

**Issue by hellomukama** [morlandi/django-ajax-datatable#17]
I would very much need this issue addressed by any of you that has succeeded with the installation.
What do i do now?

**Comment by r1bnc** [comment]
Try to check the example: https://github.com/morlandi/django-ajax-datatable/tree/master/example
https://github.com/morlandi/django-ajax-datatable/tree/master/example_minimal

Although, I am having problems with the date range. It always result in `no data in tables`.

**Comment by r1bnc** [comment]
Also see: https://github.com/morlandi/django-ajax-datatable/issues/1

**Comment by hellomukama** [comment]
thats the very one thats not working.
its the one generating that error

**Comment by morlandi** [comment]
The problem with the date range  has been clarified with @r1bnc in #18

**Comment by hellomukama** [comment]
thats the very one thats not working.
its the one generating that error

**Comment by hellomukama** [comment]
for me the whole thing from the point of installation does not work

**Comment by hellomukama** [comment]
i only tried out the system via theonline demo

**Comment by r1bnc** [comment]
Try to make a test program to make this program work.
