### ISSUE TITLE
Removing logs

### ISSUE THREAD

**Issue by mchessl** [morlandi/django-ajax-datatable#25]
Hello @morlandi !

Is there a way to remove logs ?
Thanks!

**Comment by morlandi** [comment]
Non sure which logs you're referring to.

Make sure there settings are all set to False:

```
AJAX_DATATABLE_TRACE_COLUMNDEFS = False
AJAX_DATATABLE_TRACE_QUERYDICT = False
AJAX_DATATABLE_TRACE_QUERYSET = False 
AJAX_DATATABLE_TEST_FILTERS = False 
```

Does this help ?

**Comment by mchessl** [comment]
Thanks it was exactly that !
