### ISSUE TITLE
If csrftoken cookie is set to HttpOnly, getCookie will not be able to fetch the token

### ISSUE THREAD

**Issue by shuki25** [morlandi/django-ajax-datatable#27]
Relates to issue #4 with more information.

![image](https://user-images.githubusercontent.com/31372342/118854068-7578dd00-b8a2-11eb-9d2d-9087a68f7009.png)

If a Django project setting sets the CSRF_COOKIE_HTTPONLY = True then GetCookie function will not work. It becomes a problem for us if we want to keep our site secure, including cookies to prevent CSRF. Refer to Django documentation for an alternative: [Getting CSRF token value when CSRF_COOKIE_HTTPONLY=True](https://docs.djangoproject.com/en/3.1/ref/settings/#std:setting-CSRF_COOKIE_HTTPONLY)

For more information about HttpOnly: [HTTP cookie - Secure and HttpOnly](https://en.wikipedia.org/wiki/HTTP_cookie#Secure_and_HttpOnly)

**Comment by morlandi** [comment]
Very interesting; thank you !
I'll cope with it asap

**Comment by morlandi** [comment]
Fixed merging PR #28
