### ISSUE TITLE
support for django 3.2

### ISSUE THREAD

**Issue by hypy13** [morlandi/django-ajax-datatable#33]
hi
could you please add support for django 3.2 > 
bcz im using django 3.2
but when installing this module its automatically downgrading to 3.1.6

**Comment by MathiasKowoll** [comment]
I did not have the issue, I'm running Django 3.2.4 without any issues

**Comment by morlandi** [comment]
Hello, the setup of this package does't install any dependencies at all, let alone Django.
Must be the side effect of some other package you're installing with your project.
Cheers
