### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero on filtered or empty table when selecting page

### ISSUE THREAD

**Issue by oshawa-connection** [morlandi/django-ajax-datatable#35]
Buongiorno,

We're having some problems with the server side of this library. The problem occurs when selecting " show all entries" when the table is filtered or there are no records in the table; see below.
![image](https://user-images.githubusercontent.com/36929345/127285722-1ebec296-dc40-4acf-8717-45593253ece4.png)

The minimum reproducible example app:
https://github.com/oshawa-connection/django-ajax-datatable-min-example

The error in full:
<html>
<body>
<div id="summary" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221); background: rgb(255, 255, 204); color: rgb(0, 0, 0); font-family: sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h1 style="padding: 0px; margin: 0px; font-weight: normal;">ZeroDivisionError at /ajax_datatable/permissions/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87);">integer division or modulo by zero</pre>

Request Method: | POST
-- | --
http://127.0.0.1:8000/ajax_datatable/permissions/
3.2.5
ZeroDivisionError
integer division or modulo by zero
C:\Python39\lib\site-packages\ajax_datatable\views.py, line 689, in get_response_dict
C:\Python39\python.exe
3.9.5
['C:\\Users\\fleminjw\\Documents\\temp\\django\\mysite',  'C:\\Python39\\python39.zip',  'C:\\Python39\\DLLs',  'C:\\Python39\\lib',  'C:\\Python39',  'C:\\Users\\fleminjw\\AppData\\Roaming\\Python\\Python39\\site-packages',  'C:\\Python39\\lib\\site-packages',  'C:\\Python39\\lib\\site-packages\\win32',  'C:\\Python39\\lib\\site-packages\\win32\\lib',  'C:\\Python39\\lib\\site-packages\\Pythonwin']
Wed, 28 Jul 2021 07:50:28 +0000

</div><div id="explanation" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221); background: rgb(238, 238, 238); color: rgb(0, 0, 0); font-family: sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="padding: 0px; margin: 0px;">You’re seeing this error because you have<span> </span><code style="padding: 0px; margin: 0px; font-size: 10.5625px; white-space: pre-wrap;">DEBUG = True</code><span> </span>in your Django settings file. Change that to<span> </span><code style="padding: 0px; margin: 0px; font-size: 10.5625px; white-space: pre-wrap;">False</code>, and Django will display a standard page generated by the handler for this status code.</p></div>
</body>
</html>

We are happy to provide a PR for this issue if necessary.
Django==3.2.5
django-ajax-datatable==4.2.1

Cordiali saluti

**Comment by morlandi** [comment]
Should be fixed now, and published with version 4.3.0
Thank you @oshawa-connection for reporting the bug

**Comment by oshawa-connection** [comment]
Figo, grazie mille! Lo proverò presto.
