### ISSUE TITLE
Could not override get_initial_queryset anymore

### ISSUE THREAD

**Issue by tboulogne** [morlandi/django-ajax-datatable#37]
Hello @morlandi,

Just update to the last version, and i could not override get_initial_queryset.

Any change on your side ?

Thanks for all.

Regards

**Comment by morlandi** [comment]
Not at all !
Did you specify the "request" parameter ?

I believe it has been added to the signature of the method:

    def get_initial_queryset(self, request=None)

however ... a lot of time ago ;)


P.S. Nice to hear of you again @tboulogne. Hope you're well and safe

**Comment by tboulogne** [comment]
Aah got it ! (sorry)
When multiple datatables are sharing same model, the first override all others :-). So i manage this with only one datatable and kwargs in get_initial_queryset. My bad !

PS : We are well and safe there. Hope it's same on your side @morlandi .
