### ISSUE TITLE
Disable row-details

### ISSUE THREAD

**Issue by delegate-it** [morlandi/django-ajax-datatable#39]
Hi

Thanks for the great tool.

I was wondering if there is a way to disable the row-details. my datatable contains edit button on each row. I am having a problem with my edit button if clicked, the row-details shows and then I am taken to the edit page. Is there a way to disable the row-details so it doesn't show when the edit button is clicked?

**Comment by morlandi** [comment]
Hello,
row-details should be disabled by default, unless you explicitly specify `full_row_select = true` as extra option to initialize_table():

```
        $( document ).ready(function() {
            AjaxDatatableViewUtils.initialize_table(
                $('#datatable'),
                "{% url 'frontend:ajax_datatable_permissions' %}",
                {
                    // extra_options (example)
                    processing: false,
                    autoWidth: false,
                    full_row_select: true,
                    scrollX: false
                }, {
                    // extra_data
                    // ...
                },
                );
        });
```

Could you check this ?
Mario
