### ISSUE TITLE
issue with CSRF token

### ISSUE THREAD

**Issue by samerda75** [morlandi/django-ajax-datatable#4]
i am using Django with the 
but i am always getting this error Forbidden (CSRF token missing or incorrect.)

i have tried to include the token within the AjaxDatatableViewUtils.initialize_table but not failed to do so
can you please advice 
i am using the below script 

    <script language="javascript">

        $( document ).ready(function() {
        var crf_token = $('[name="csrfmiddlewaretoken"]').attr('value');
            AjaxDatatableViewUtils.initialize_table(
                $('#datatable-customer'),
                "{% url 'crm:ajax_datatable_customer' %}",
                {
                    // extra_options (example)
                    processing: false,
                    autoWidth: false,
                    full_row_select: false,
                    scrollX: false
                }, {
                    // extra_data
                    // ...
                },
            );
        });

    </script>

**Comment by morlandi** [comment]
mmmh this is puzzling, since the library does a couple of POSTS via Ajax, and  in both cases CSRF token in correctly sent:

file `ajax_datatable/static/ajax_datatable/js/utils.js` (line 341):

```
    $.ajax({
        type: 'POST',
        url: url,
        data: data,
        dataType: 'json',
        headers: {'X-CSRFToken': getCookie('csrftoken')}
    }).done(function(data, textStatus, jqXHR) {
```

file `ajax_datatable/static/ajax_datatable/js/utils.js` (line 398):

```
  $.ajax({
      type: 'POST',
      url: url,
      data: data,
      dataType: 'json',
      cache: false,
      crossDomain: false,
      headers: {'X-CSRFToken': getCookie('csrftoken')}
  }).done(function(data, textStatus, jqXHR) {
```

where:

```
    function getCookie(name) {
        var value = '; ' + document.cookie,
            parts = value.split('; ' + name + '=');
        if (parts.length == 2) return parts.pop().split(';').shift();
    }
```

so there is no need to supply it to AjaxDatatableViewUtils.initialize_table()

**Comment by samerda75** [comment]
Thank you for your reply i was missing loading one js file and it works now, 

can i add a button like edit or other button for every row inside the table ?  i usual do this by adding  "columns": [] inside the datatable definition

**Comment by samerda75** [comment]
i am using this code 
                    "columns":[
                        { "render": function ( data, type, full, meta )
                            {
                                var buttonID = full.id;
                                var edit_url = "{% url 'crm:edit_customer' 12345 %}".replace(/12345/, buttonID.toString());
                                var edit_salesrep_url = "{% url 'crm:edit_customer_sales_rep' 12345 %}".replace(/12345/, buttonID.toString());
                                var edit_loc_url = "{% url 'crm:edit_customer_location' 12345 %}".replace(/12345/, buttonID.toString());
                                var delete_url = "{% url 'crm:delete_customer' 12345 %}".replace(/12345/, buttonID.toString());
                                var result = ''

                                {% if perms.crm.change_customer %}
                                    result = result + (`<button type="button" class="edit-customer btn btn-outline-warning effect waves-light btn-xs" data-id=${edit_url} title="{% trans "Edit" %}"><i class="fe-edit"></i></button>`)
                                {% else %}
                                    {% if perms.crm.sales_rep_change_customer %}
                                        result = result + (`<button type="button" class="edit-customer-sales-rep btn btn-outline-warning effect waves-light btn-xs" data-id=${edit_salesrep_url} title="{% trans "Edit" %}"><i class="fe-edit"></i></button>`)
                                    {% endif %}
                                {% endif %}
                                {% comment %}
                                {% if perms.crm.change_location_customer %}
                                    result = result + (`<button type="button" class="edit-customer-location btn btn-outline-info effect waves-light btn-xs" data-id=${edit_loc_url} title="{% trans "Edit" %}"><i class="fe-map-pin"></i></button>`)
                                {% endif %}
                                {% endcomment %}
                                {% if perms.crm.delete_customer %}
                                    result = result + (`<button type="button" class="edit-customer btn btn-outline-danger effect waves-light btn-xs" data-id=${delete_url} title="{% trans "Edit" %}"><i class="fe-trash"></i></button>`)
                                {% endif %}
                                return result
                            }
                        }
                    ]

**Comment by samerda75** [comment]
> mmmh this is puzzling, since the library does a couple of POSTS via Ajax, and in both cases CSRF token in correctly sent:
> 
> file `ajax_datatable/static/ajax_datatable/js/utils.js` (line 341):
> 
> ```
>     $.ajax({
>         type: 'POST',
>         url: url,
>         data: data,
>         dataType: 'json',
>         headers: {'X-CSRFToken': getCookie('csrftoken')}
>     }).done(function(data, textStatus, jqXHR) {
> ```
> 
> file `ajax_datatable/static/ajax_datatable/js/utils.js` (line 398):
> 
> ```
>   $.ajax({
>       type: 'POST',
>       url: url,
>       data: data,
>       dataType: 'json',
>       cache: false,
>       crossDomain: false,
>       headers: {'X-CSRFToken': getCookie('csrftoken')}
>   }).done(function(data, textStatus, jqXHR) {
> ```
> 
> where:
> 
> ```
>     function getCookie(name) {
>         var value = '; ' + document.cookie,
>             parts = value.split('; ' + name + '=');
>         if (parts.length == 2) return parts.pop().split(';').shift();
>     }
> ```
> 
> so there is no need to supply it to AjaxDatatableViewUtils.initialize_table()
Thank you for your reply i was missing loading one js file and it works now,

can i add a button like edit or other button for every row inside the table ? i usual do this by adding "columns": [] inside the datatable definition

                    "columns":[
                        { "render": function ( data, type, full, meta )
                            {
                                var buttonID = full.id;
                                var edit_url = "{% url 'crm:edit_customer' 12345 %}".replace(/12345/, buttonID.toString());
                                var edit_salesrep_url = "{% url 'crm:edit_customer_sales_rep' 12345 %}".replace(/12345/, buttonID.toString());
                                var edit_loc_url = "{% url 'crm:edit_customer_location' 12345 %}".replace(/12345/, buttonID.toString());
                                var delete_url = "{% url 'crm:delete_customer' 12345 %}".replace(/12345/, buttonID.toString());
                                var result = ''

                                {% if perms.crm.change_customer %}
                                    result = result + (`<button type="button" class="edit-customer btn btn-outline-warning effect waves-light btn-xs" data-id=${edit_url} title="{% trans "Edit" %}"><i class="fe-edit"></i></button>`)
                                {% else %}
                                    {% if perms.crm.sales_rep_change_customer %}
                                        result = result + (`<button type="button" class="edit-customer-sales-rep btn btn-outline-warning effect waves-light btn-xs" data-id=${edit_salesrep_url} title="{% trans "Edit" %}"><i class="fe-edit"></i></button>`)
                                    {% endif %}
                                {% endif %}
                                {% comment %}
                                {% if perms.crm.change_location_customer %}
                                    result = result + (`<button type="button" class="edit-customer-location btn btn-outline-info effect waves-light btn-xs" data-id=${edit_loc_url} title="{% trans "Edit" %}"><i class="fe-map-pin"></i></button>`)
                                {% endif %}
                                {% endcomment %}
                                {% if perms.crm.delete_customer %}
                                    result = result + (`<button type="button" class="edit-customer btn btn-outline-danger effect waves-light btn-xs" data-id=${delete_url} title="{% trans "Edit" %}"><i class="fe-trash"></i></button>`)
                                {% endif %}
                                return result
                            }
                        }
                    ]

**Comment by samerda75** [comment]
> mmmh this is puzzling, since the library does a couple of POSTS via Ajax, and in both cases CSRF token in correctly sent:
> 
> file `ajax_datatable/static/ajax_datatable/js/utils.js` (line 341):
> 
> ```
>     $.ajax({
>         type: 'POST',
>         url: url,
>         data: data,
>         dataType: 'json',
>         headers: {'X-CSRFToken': getCookie('csrftoken')}
>     }).done(function(data, textStatus, jqXHR) {
> ```
> 
> file `ajax_datatable/static/ajax_datatable/js/utils.js` (line 398):
> 
> ```
>   $.ajax({
>       type: 'POST',
>       url: url,
>       data: data,
>       dataType: 'json',
>       cache: false,
>       crossDomain: false,
>       headers: {'X-CSRFToken': getCookie('csrftoken')}
>   }).done(function(data, textStatus, jqXHR) {
> ```
> 
> where:
> 
> ```
>     function getCookie(name) {
>         var value = '; ' + document.cookie,
>             parts = value.split('; ' + name + '=');
>         if (parts.length == 2) return parts.pop().split(';').shift();
>     }
> ```
> 
> so there is no need to supply it to AjaxDatatableViewUtils.initialize_table()

Thank you for your support

**Comment by morlandi** [comment]
You're welcome.

I just added an example showing how to add a column with a button; this should be done python-side rather then javascript-side:

https://github.com/morlandi/django-ajax-datatable#81adding-a-button-for-editing

I will close this issue; feel free to open a new one in case

**Comment by shuki25** [comment]
It appears that it doesn't really work.  I checked the request header and it is not showing 'X-CSRFToken' at all.  It didn't work in both Safari and Firefox, so it's not the browser. The csrftoken cookie is set but the script is not passing that header for some reason. So I had to add csrfmiddlewaretoken in the extra_field to make it work.

**Comment by morlandi** [comment]
@shuki25 I do believe it does. Could you please check on the demo site http://django-ajax-datatable-demo.brainstorm.it/tracks/ ?

<img width="1254" alt="Screenshot 2021-05-19 at 09 42 53" src="https://user-images.githubusercontent.com/299854/118775103-dabed500-b886-11eb-8eae-cbfe96f80866.png">

**Comment by shuki25** [comment]
@morlandi I'm opening up a new issue, I figure out what went wrong and you might want to figure out an alternative method.
