### ISSUE TITLE
request.is_ajax() is returning false

### ISSUE THREAD

**Issue by Shavinder** [morlandi/django-ajax-datatable#48]
I have followed the steps and trying to use the plugin in a simple way, but I am getting an assertion error. I have looked views.py line number 381, request.is_ajax()

**Comment by Shavinder** [comment]
Ah, I just came across the previous issue with the same error and found out my mistake. The ajax view is not to be called directly.  View number one generates the HTML page which contains a table markup as well as the script which calls the ajax view. Its working now. Thanks, Morlandi!

**Comment by morlandi** [comment]
ok, grad problem in over ;)
