### ISSUE TITLE
How to ise Tailwindcss classes

### ISSUE THREAD

**Issue by Shavinder** [morlandi/django-ajax-datatable#49]
I ve tried to apply tailwindcss classes using tailwind's customised stylesheet. The classes get picked up in the markup  but are not applied. They are being overridden by other styles. Perhaps datatables stylesheet. I ve tried moving the tailwind inclusion in the base template to after the datatable css but it does not work.  Can you help me please?

**Comment by morlandi** [comment]
I'm sorry ... .I don't know anything about tailwindcss
