### ISSUE TITLE
Pass *args **kwargs  to get_initial_queryset()

### ISSUE THREAD

**Issue by LukeWebbJacobs** [morlandi/django-ajax-datatable#50]
Hi, I had to monkey patch get like this:

    def get(self, request, *args, **kwargs):
        self.milestone = kwargs['milestone']
        return super(TaskListInProgAPI, self).get(request, *args, **kwargs)

so that I could read my url paramters. We could pass these directly to get_initial_queryset()? Is there another way to use these when overriding get_initial_queryset()?

**Comment by etiennepouliot** [comment]
Try this :
```
def get_initial_queryset(self, request=None):
    milestone = request.resolver_match.kwargs['milestone']
    ...
```

**Comment by LukeWebbJacobs** [comment]
Awesome thank you, that works great. Basic django knowledge lacking here sorry!
