### ISSUE TITLE
implement datatable on abstract model and get data from submodels

### ISSUE THREAD

**Issue by RobinPalletFly** [morlandi/django-ajax-datatable#59]
I have a base abstract model which other models inherit from.  Is there a way for AjaxDatatableView to take this class and display data from all of the objects of the inherited models?

**Comment by etiennepouliot** [comment]
I also use an abstract model and everything is working fine.

Did you define your columns_def ?

**Comment by morlandi** [comment]
You might want to try using get_column_defs() instead of defining a static columns_def list.
This way, you could adjust the list of columns at runtime.
I never did it, however.
