### ISSUE TITLE
Anyleads about how to implement "multiple choices" field for filtering columns ?

### ISSUE THREAD

**Issue by Joey-DP** [morlandi/django-ajax-datatable#70]
Anyleads about how to implement "multiple choices" field for filtering columns ?

**Comment by Abiruth** [comment]
Probably not the answer you're wanting but I usually create a separate filter "panel" for these, as outlined on: https://pypi.org/project/django-ajax-datatable/#add-a-sidebar-with-custom-filters

**Comment by morlandi** [comment]
Yes, I would opt for sidebar filters.
You can see those in action here:

http://django-ajax-datatable-demo.brainstorm.it/side_filters/
