### ISSUE TITLE
Border : 1px added in div in when 'searchable': False

### ISSUE THREAD

**Issue by vdveldet** [morlandi/django-ajax-datatable#9]
Hi,

I have a column_defs with first column a button to Edit.
This column is not searchable or order-able. So on top there should not be such elements

However there is a styling added to the div that will reassemble like this s an searchable filed but in fact this is a border.

```
class CustomerAjaxDatatableView(AjaxDatatableView):

    model = Customer
    title = 'Customer'
    initial_order = [["name", "asc"], ]
    length_menu = [[10, 20, 50, 100, -1], [10, 20, 50, 100, 'all']]
    search_values_separator = '+'

    column_defs = [
        {'name': 'edit', 'title': '', 'searchable': False, 'orderable': False, },
        {'name': 'name', 'visible': True, },
        {'name': 'address1', 'visible': True, },
        {'name': 'address2', 'visible': True, },
        {'name': 'postciode', 'visible': True, },
        {'name': 'city', 'visible': True, },
        {'name': 'country', 'visible': True, },
    ]
```

![Selection_094](https://user-images.githubusercontent.com/11089060/107005128-8be5a780-678f-11eb-845d-577abfbb8339.png)

**Comment by morlandi** [comment]
Thank you @vdveldet ... you're right.
Since I normally use AjaxDatatableView.render_row_tools_column_def() as first column, I might have styled it to obtain this:

<img width="169" alt="Screenshot 2021-02-05 at 09 04 10" src="https://user-images.githubusercontent.com/299854/107006293-37dbc280-6791-11eb-8bbe-729edf3be5d7.png">

My bad !
I'll fix this soon ;)

**Comment by vdveldet** [comment]
I just add some init now, that will help me.

```
      $(document).ready(function() {
        AjaxDatatableViewUtils.init({
            search_icon_html: '',
        });
    });

```

Thanks for the fine Django addition !

**Comment by morlandi** [comment]
Removed ;)
Thank oy @vdveldet
