### ISSUE TITLE
Package on pypi don't require installation of pytz

### ISSUE THREAD

**Issue by cla-azzarello** [morlandi/django-ajax-datatable#93]
I installed by "pip install django-ajax-datatable".

Current version installed 4.4.4 

The requested package pytz is not installed by pip. I had to install manually.

**Comment by adelsonllima** [comment]
up

**Comment by morlandi** [comment]
Thank you both; hopefully will fix soon

**Comment by morlandi** [comment]
or even better: remove this dependency ;)

**Comment by cla-azzarello** [comment]
This should be fixed with commit 5c9dce4 . I've not tested it, but I think the issue can be closed.

**Comment by morlandi** [comment]
Thank you @cla-azzarello ... yes, I think I got rid of `pytz` long ago, so let's close the issue ;)
