### ISSUE TITLE
Accessing request in customize_row()

### ISSUE THREAD

**Issue by bitwiseoperations** [morlandi/django-ajax-datatable#96]
Hello,

I'm currently trying to modify a cell in a row for some of my tables, depending on the status of another object which the main object is is a foreign key for. Unlike with the other overrideable methods it seems I can't just add request=None to the params, is there any other way for me to do this?

Kind regards,
Nestor

**Comment by Mike3285** [comment]
I think you can just access it on `self.request`

**Comment by bitwiseoperations** [comment]
Hi Mike,

Yep, I can. Thank you for your help, I feel a bit of a fool now... But at least I know.
