### ISSUE TITLE
Remove left +/- column

### ISSUE THREAD

**Issue by MichaelDacanay** [morlandi/django-ajax-datatable#99]
Is it possible to remove the +/- on the left column beside each row in the tab? Currently, when pressed, the page seems to refresh back at the top instead of staying in-place. This behavior doesn't show up when clicking on the row itself; the data expands fine.

**Comment by cnagytcorp** [comment]
in your column_defs what is the first column ? {'name': 'edit', 'title': 'Edit', 'placeholder': True, 'searchable': False, 'orderable': False, }
remove it

**Comment by MichaelDacanay** [comment]
My first column was `{'name': 'id', 'visible': False, 'orderable': True, }`. The +/- remain when I remove it.

**Comment by cnagytcorp** [comment]
check the [Add row tools as first column]
at https://github.com/cnagytcorp/django-ajax-datatable#id29

**Comment by MichaelDacanay** [comment]
Ohh, thank you! I didn't notice that `AjaxDatatableView.render_row_tools_column_def()` was the first item in the list.
